### ISSUE TITLE
Nice work

### ISSUE THREAD

**Issue by huixiancheng** [WangFeng18/Swin-Transformer#1]
Have you try to support Non-square window-size?
I take a try base on another unoffical [repo](https://github.com/berniwal/swin-transformer-pytorch). Look not good sice i'm a green hand.

**Comment by WangFeng18** [comment]
I believe it's easy to modify our codes to adapt to non-square window. If you have interests, you can have a try.

**Comment by huixiancheng** [comment]
thx 🙇
